### ISSUE TITLE
Persian Animal Jokes :) 

### ISSUE THREAD

**Issue by Alpha2Shahiri** [Ipuch/animal-puns#15]
چرا ماهی‌ها هیچ‌وقت اینترنت ندارند؟
چون از شبکه‌ها می‌ترسند!

Translation:
Why do fish never use the internet?
Because they are afraid of the 'net'

**Comment by Ipuch** [comment]
That's a great idea, you can add a new section to the readme.md
In farsi with nationflag ! :)
